### ISSUE TITLE
Cannot find module ffe-icons-react/svg.sprite.config.json

### ISSUE THREAD

**Issue by oskaremil** [SpareBank1/designsystem#66] opened 2018-03-08 09:51 UTC
#### Which package is this issue related to?
ffe-icons-react
#### Describe your issue (screenshots welcome!)
```
> @sb1/ffe-details-list-react@2.0.2 build /mnt/c/Workspace/sparebank1-designsystem/packages/ffe-details-list-react
> babel -d lib/. --ignore=*.spec.js src/.

src/Detail.js -> lib/Detail.js
src/DetailContent.js -> lib/DetailContent.js
src/DetailList.js -> lib/DetailList.js
src/index.js -> lib/index.js

> @sb1/ffe-header@11.0.2 build /mnt/c/Workspace/sparebank1-designsystem/packages/ffe-header
> lessc less/ffe-header-nodeps.less examples/ffe-header.css --autoprefix && lessc examples/examples.less examples/examples.css

lerna ERR! build Errored while running script in '@sb1/ffe-icons-react'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! module.js:549
lerna ERR!     throw err;
lerna ERR!     ^
lerna ERR!
lerna ERR! Error: Cannot find module '../../../../designsystem/packages/ffe-icons-react/svg.sprite.config.json'
lerna ERR!     at Function.Module._resolveFilename (module.js:547:15)
lerna ERR!     at Function.Module._load (module.js:474:25)
lerna ERR!     at Module.require (module.js:596:17)
lerna ERR!     at require (internal/module.js:11:18)
lerna ERR!     at Object.<anonymous> (/mnt/c/Workspace/sparebank1-designsystem/packages/ffe-icons/bin/build.js:42:18)
lerna ERR!     at Module._compile (module.js:652:30)
lerna ERR!     at Object.Module._extensions..js (module.js:663:10)
lerna ERR!     at Module.load (module.js:565:32)
lerna ERR!     at tryModuleLoad (module.js:505:12)
lerna ERR!     at Function.Module._load (module.js:497:3)
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @sb1/ffe-icons-react@5.0.2 ffe:icons: `ffe-icons --opts=designsystem/packages/ffe-icons-react/svg.sprite.config.json`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @sb1/ffe-icons-react@5.0.2 ffe:icons script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /home/oes/.npm/_logs/2018-03-08T09_48_10_381Z-debug.log
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @sb1/ffe-icons-react@5.0.2 build: `npm run ffe:icons && npm run build:jsx-components && npm run build:babel`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @sb1/ffe-icons-react@5.0.2 build script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /home/oes/.npm/_logs/2018-03-08T09_48_10_403Z-debug.log
lerna ERR!
lerna ERR! > @sb1/ffe-icons-react@5.0.2 build /mnt/c/Workspace/sparebank1-designsystem/packages/ffe-icons-react
lerna ERR! > npm run ffe:icons && npm run build:jsx-components && npm run build:babel
lerna ERR!
lerna ERR!
lerna ERR! > @sb1/ffe-icons-react@5.0.2 ffe:icons /mnt/c/Workspace/sparebank1-designsystem/packages/ffe-icons-react
lerna ERR! > ffe-icons --opts=designsystem/packages/ffe-icons-react/svg.sprite.config.json
lerna ERR!
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/mnt/c/Workspace/sparebank1-designsystem/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm run build
module.js:549
    throw err;
    ^
```
#### What is the expected behavior? 
Packages are built and development server is started
#### What is the actual behavior?
npm error message on build
#### Steps to reproduce

- Fresh clone from `master` (commit `29bb1cf0cb4795a11cbcb8cd917b10560b56d5eb`)
- Using node v8.10.0
- Using npm 5.7.1

1. Run `npm install`
1. Run `npm start` at root to  build all packages and start local development server

**Comment by wkillerud** [comment] 2018-03-08 10:36
Thanks for the detailed bug report @oskaremil :+1: I'm afraid I can't reproduce the issue though.

Tested `29bb1cf0cb4795a11cbcb8cd917b10560b56d5eb` using Node v8.9.4 and npm 5.6.0 on Ubuntu Linux 17.10. Ran `npm install` and `npm start`, and I did not get the error you describe.

```
[...]
> @sb1/ffe-icons-react@5.0.2 ffe:icons /home/virtualbox/git/designsystem/packages/ffe-icons-react
> ffe-icons --opts=designsystem/packages/ffe-icons-react/svg.sprite.config.json

2018-03-08 11:21:44 - info: Created spriter instance
2018-03-08 11:21:44 - info: Compiling 143 shapes ...
2018-03-08 11:21:44 - info: Laying out «symbol» sprite («symbol» mode)
2018-03-08 11:21:44 - info: Laying out «view» sprite («view» mode)
2018-03-08 11:21:45 - info: Finished «symbol» + «view» sprite compilation
2018-03-08 11:21:45 - info: Created 2 x SVG, 1 x HTML, 1 x JS
[...]
```

Also tested a fresh clone on Windows using Git Bash since it looks from the paths in your stack trace that you may be on Windows? In any case, I tested using Node v8.6.0 and npm 5.3.0 on commit `29bb1cf0cb4795a11cbcb8cd917b10560b56d5eb`. Ran `npm install` and `npm start` and got the expected OK result. 

```
[...]
> @sb1/ffe-icons-react@5.0.2 ffe:icons C:\git\designsystem\packages\ffe-icons-react
> ffe-icons --opts=designsystem/packages/ffe-icons-react/svg.sprite.config.json

2018-03-08 11:27:23 - info: Created spriter instance
2018-03-08 11:27:23 - info: Compiling 143 shapes ...
2018-03-08 11:27:23 - info: Laying out «symbol» sprite («symbol» mode)
2018-03-08 11:27:23 - info: Laying out «view» sprite («view» mode)
2018-03-08 11:27:23 - info: Finished «symbol» + «view» sprite compilation
2018-03-08 11:27:23 - info: Created 2 x SVG, 1 x HTML, 1 x JS
[...]
```

Considering it _Works On My Machine_ :sparkles: and on Travis CI I think this is an issue with your setup rather than a bug in FFE.

**Comment by wkillerud** [comment] 2018-03-08 10:38
The second I finished writing the above I think I spotted the issue. The command requires the folder name of the repo be `designsystem` for path reasons (the package has to traverse up _n_ directories to find the config when the package is used due to how scoping works with `node_modules/`. I see your folder is named `sparebank1-designsystem`. If you rename it it should work @oskaremil .

**Comment by wkillerud** [comment] 2018-03-08 10:40
Hm, this is a poor developer experience and an issue we haven't considered. I'll create a new issue to see if we can improve things so we don't put constraints on the folder name.

**Comment by wkillerud** [comment] 2018-03-08 10:47
We'll track progress on this issue on #67, so I'll close this one for now. A workaround while you wait for a fix is to name the folder `designsystem`.

**Closed as completed by wkillerud** 2018-03-08 10:47 UTC
Labels: :bug: Bug

**Comment by oskaremil** [comment] 2018-03-08 19:39
Thank you. 

BTW, running in Ubuntu on Windows. 

When I tried to run on Windows some package (don't remember which) throws an error because command 'cp' is not found.
